# Assignment 3

# Question 1:

In [1]:
import numpy as np

In [2]:
arr = np.arange(2, 50, 3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Questions 2:

In [12]:
lst1 = [2,4,5,1,3]
lst2 = [7,6,9,8,10]

a1 = np.array(lst1) 
print(a1) 
 
a2 = np.array(lst2) 
print(a2) 

# a3 = np.append(a1, a2) 
# print(a3) 

m = np.concatenate((a1,a2)) 
print(m)

np.sort(m)        #sorting

[2 4 5 1 3]
[ 7  6  9  8 10]
[ 2  4  5  1  3  7  6  9  8 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Questions 3:

In [16]:
arr = np.array( [[ 1, 3, 2],[ 4, 6, 5]])

print("Dimension:",arr.ndim)
 
print("Size:",arr.size)

Dimension: 2
Size: 6


# Questions 4:

In [18]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [19]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [21]:
a2 = a[:,np.newaxis]
a2.shape

(6, 1)

In [22]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [23]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [24]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [30]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [33]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

# Questions 5:

In [34]:
#Vertically

n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [35]:
#Horizontally

n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

# Question 6:

In [38]:
arr = np.array([1, 2, 4, 1, 6, 2, 8, 9, 1, 2, 3]) 
  
uni, freq = np.unique(arr, return_counts = True) 

print("Unique Values:",  uni) 
  
print("Frequency Values:", freq)

new = set(arr) 
print("Counts:", len(new))

Unique Values: [1 2 3 4 6 8 9]
Frequency Values: [3 3 1 1 1 1 1]
Counts: 7
